version: "3.9"

services:
  techtask:
    restart: always
    container_name: tech-task
    build: .

    ports:
      - "8000:8000"

    environment:
      DATABASE_HOST: "db"
      POSTGRES_USER: "postgres"
      POSTGRES_DB: "postgres"
      DB_PASSWORD: "password"
    volumes:
      - .:/app
#    command:
#      - docker run --name db -d -e POSTGRES_PASSWORD=password -e POSTGRES_USER=password postgres
    depends_on:
      - db
    networks:
      - fullstack

    entrypoint: ['go', 'run', 'cmd/main.go']



  db:
    restart: always
    image: postgres:latest
    container_name: database
    volumes:
      - database_postgres:/var/lib/postgresql/data

    environment:
      POSTGRES_PASSWORD: "password"
      POSTGRES_USER: "postgres"
      POSTGRES_DB: "postgres"

    ports:
      - "5438:5432"
    networks:
      - fullstack

volumes:
  database_postgres:

networks:
  fullstack:
    driver: bridge
