version: "3.9"

services:
  techtask:
    restart: always
    container_name: tech-task
    build: .

    ports:
      - "8000:8000"

    environment:
      DATABASE_HOST: "db"
      POSTGRES_USER: "postgres"
      POSTGRES_DB: "postgres"
      DB_PASSWORD: "111111"
    volumes:
      - .:/app
    depends_on:
      - db
    entrypoint: ['go', 'run', 'cmd/main.go']



  db:
    restart: always
    image: postgres:latest

    volumes:
      - ./.database/postgres/data:/var/lib/postgresql/data

    environment:
      POSTGRES_PASSWORD: "password"
      POSTGRES_USER: "postgres"
      POSTGRES_DB: "postgres"

    ports:
      - "5438:5432"

